config/routes.rb
# frozen_string_literal: true

# rubocop:enable
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :ingredients, only: [:new, :create]
  end
  resources :doses, only: :destroy
  resources :ingredients, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true

# rubocop:enable
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
# frozen_string_literal: true

# rubocop:enableclass Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient, message: 'Please choose another dose!' }
  validates :description, presence: true
end

app/models/ingredient.rb
# frozen_string_literal: true

# rubocop:enable
class Ingredient < ApplicationRecord
  has_many :doses
  #has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

# rubocop:enable
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %(':show, :edit, :update, :destroy)

  # GET /cocktails
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  def show; end

  def create
    @cocktail = Cocktail.new(pet_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render 'edit'
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktail_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
# frozen_string_literal: true

# rubocop:enable
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.coktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:decription, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

# rubocop:enable
class IngredientsController < ApplicationController

def create
def new
  @dose = Dose.find(params[:dose_id])
  @ingredient = Ingredient.new(dose_params)
  @ingredient.dose =
end

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/_index.html.erb
<p id="notice"><%= notice %></p>

<h1><p id="notice"><%= notice %></p>

<h1><p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>s</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New cocktail', new_cocktail_path %>

app/views/cocktails/_new.html.erb
_new.html.erb

app/views/cocktails/_show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @cocktail.banner_url %>')">
  <h1><%= @cocktail.name %></h1>
</div>

<div class="container">
  <div class="row">
    <% @cocktail.ingredients.each do |ingredient| %>
      <div class="col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= ingredient.image_url %>');">
          <div class="card-tags">
            <% ingredient.ingredient_tags.each do |ingredient_tag| %>
              <span>
                <%= ingredient_tag.tag.name %>
                <%= link_to ingredient_path(ingredient_tag), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </span>
            <% end %>
            <%= link_to new_ingredient_ingredient_path(ingredient) do %>
              <i class="fas fa-plus"></i>
            <% end %>
          </div>
          <div class="card-description">
            <h2><%= ingredient.name %></h2>
          </div>
          <%= link_to "+", ingredient_path(ingredient), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h4>Add a ingredient:</h4>
      <%= simple_form_for [ @cocktail, @ingredient ] do |f| %>
        <%= f.input :name, placeholder: "Mojito" %>
        <%= f.input :image_url, placeholder: ".jpg" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
      <button class="btn btn-secondary toggle-form">Toggle form</button>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<h1>Edit a reciepe</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h1>Add new amount for <%= @dose.name %></h1>

      <%= simple_form_for [@ingredient, @dose] do |f| %>
        <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, class: 'multiple-select' }, include_hidden: false %>
        <%= f.submit "Add amount", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>